import type { Asset } from "@/lib/types";

export const assets: Asset[] = [
  {
    id: "asset-det-cv-01",
    plantId: "detroit-hq",
    lineId: "det-seat-line-a",
    code: "CV-DET-01",
    name: "Detroit Main Conveyor",
    assetType: "conveyor",
    status: "watch",
    lastMaintenanceAt: "2026-04-05T08:30:00Z",
    playbookCode: "PB-CONVEYOR-BEARING",
    zoneLabel: "Kitting Transfer",
  },
  {
    id: "asset-det-pr-01",
    plantId: "detroit-hq",
    lineId: "det-seat-line-a",
    code: "PR-DET-01",
    name: "Detroit Forming Press",
    assetType: "hydraulic-press",
    status: "healthy",
    lastMaintenanceAt: "2026-04-16T12:00:00Z",
    playbookCode: "PB-PRESS-PRESSURE",
    zoneLabel: "Frame Form Cell",
  },
  {
    id: "asset-war-rw-01",
    plantId: "warren-mi",
    lineId: "war-seat-line-a",
    code: "RW-WAR-01",
    name: "Warren Robotic Welder 01",
    assetType: "robotic-welder",
    status: "critical",
    lastMaintenanceAt: "2026-03-29T10:15:00Z",
    playbookCode: "PB-WELDER-THERMAL",
    zoneLabel: "Seat Line A Weld Cell",
  },
  {
    id: "asset-war-cv-01",
    plantId: "warren-mi",
    lineId: "war-seat-line-a",
    code: "CV-WAR-01",
    name: "Warren Feed Conveyor",
    assetType: "conveyor",
    status: "warning",
    lastMaintenanceAt: "2026-04-10T09:00:00Z",
    playbookCode: "PB-CONVEYOR-BEARING",
    zoneLabel: "Seat Line A Infeed",
  },
  {
    id: "asset-war-pr-01",
    plantId: "warren-mi",
    lineId: "war-seat-line-b",
    code: "PR-WAR-01",
    name: "Warren Clamp Press",
    assetType: "hydraulic-press",
    status: "healthy",
    lastMaintenanceAt: "2026-04-18T13:45:00Z",
    playbookCode: "PB-PRESS-PRESSURE",
    zoneLabel: "Seat Line B Clamp Station",
  },
  {
    id: "asset-eas-pr-01",
    plantId: "eastaboga-al",
    lineId: "eas-seat-line-a",
    code: "PR-EAS-01",
    name: "Eastaboga Hydraulic Press 01",
    assetType: "hydraulic-press",
    status: "warning",
    lastMaintenanceAt: "2026-04-02T14:45:00Z",
    playbookCode: "PB-PRESS-PRESSURE",
    zoneLabel: "Seat Pan Form Cell",
  },
  {
    id: "asset-eas-cv-01",
    plantId: "eastaboga-al",
    lineId: "eas-seat-line-a",
    code: "CV-EAS-01",
    name: "Eastaboga Outfeed Conveyor",
    assetType: "conveyor",
    status: "healthy",
    lastMaintenanceAt: "2026-04-14T07:20:00Z",
    playbookCode: "PB-CONVEYOR-BEARING",
    zoneLabel: "Seat Line A Outfeed",
  },
  {
    id: "asset-lan-rw-01",
    plantId: "lansing-mi",
    lineId: "lan-seat-line-a",
    code: "RW-LAN-01",
    name: "Lansing Robotic Welder 01",
    assetType: "robotic-welder",
    status: "warning",
    lastMaintenanceAt: "2026-04-01T11:00:00Z",
    playbookCode: "PB-WELDER-THERMAL",
    zoneLabel: "Seat Line A Weld Station",
  },
  {
    id: "asset-lan-cv-01",
    plantId: "lansing-mi",
    lineId: "lan-console-line-b",
    code: "CV-LAN-01",
    name: "Lansing Console Conveyor",
    assetType: "conveyor",
    status: "watch",
    lastMaintenanceAt: "2026-04-17T15:10:00Z",
    playbookCode: "PB-CONVEYOR-BEARING",
    zoneLabel: "Console Line B Transfer",
  },
];
