import type { AssetType, SensorTemplate } from "@/lib/types";

export const sensorTemplatesByAssetType: Record<AssetType, SensorTemplate[]> = {
  conveyor: [
    {
      key: "vibration",
      label: "Vibration RMS",
      unit: "mm/s",
      direction: "up",
      baseValue: 1.3,
      healthyVariance: 0.08,
      warningDelta: 0.55,
      criticalDelta: 0.95,
      weight: 1.15,
    },
    {
      key: "motor-temperature",
      label: "Motor Temperature",
      unit: "deg C",
      direction: "up",
      baseValue: 54,
      healthyVariance: 0.9,
      warningDelta: 7.5,
      criticalDelta: 12,
      weight: 1,
    },
    {
      key: "motor-current",
      label: "Motor Current",
      unit: "A",
      direction: "up",
      baseValue: 18.2,
      healthyVariance: 0.4,
      warningDelta: 2.2,
      criticalDelta: 4.4,
      weight: 0.9,
    },
    {
      key: "belt-speed",
      label: "Belt Speed",
      unit: "m/s",
      direction: "down",
      baseValue: 1.22,
      healthyVariance: 0.03,
      warningDelta: 0.13,
      criticalDelta: 0.22,
      weight: 0.8,
    },
  ],
  "robotic-welder": [
    {
      key: "tip-temperature",
      label: "Tip Temperature",
      unit: "deg C",
      direction: "up",
      baseValue: 486,
      healthyVariance: 4.2,
      warningDelta: 40,
      criticalDelta: 76,
      weight: 1.25,
    },
    {
      key: "current-draw",
      label: "Current Draw",
      unit: "A",
      direction: "unstable",
      baseValue: 82,
      healthyVariance: 1.1,
      warningDelta: 9,
      criticalDelta: 16,
      weight: 1.1,
    },
    {
      key: "cycle-time",
      label: "Cycle Time",
      unit: "sec",
      direction: "up",
      baseValue: 4.1,
      healthyVariance: 0.05,
      warningDelta: 0.55,
      criticalDelta: 0.95,
      weight: 1.05,
    },
    {
      key: "vibration",
      label: "Arm Vibration",
      unit: "mm/s",
      direction: "up",
      baseValue: 0.72,
      healthyVariance: 0.04,
      warningDelta: 0.28,
      criticalDelta: 0.44,
      weight: 0.9,
    },
  ],
  "hydraulic-press": [
    {
      key: "hydraulic-pressure",
      label: "Hydraulic Pressure",
      unit: "psi",
      direction: "unstable",
      baseValue: 3020,
      healthyVariance: 18,
      warningDelta: 180,
      criticalDelta: 320,
      weight: 1.2,
    },
    {
      key: "oil-temperature",
      label: "Oil Temperature",
      unit: "deg C",
      direction: "up",
      baseValue: 63,
      healthyVariance: 0.8,
      warningDelta: 6.4,
      criticalDelta: 11,
      weight: 0.95,
    },
    {
      key: "cycle-deviation",
      label: "Cycle Deviation",
      unit: "sec",
      direction: "up",
      baseValue: 0.18,
      healthyVariance: 0.02,
      warningDelta: 0.17,
      criticalDelta: 0.28,
      weight: 1,
    },
    {
      key: "motor-current",
      label: "Motor Current",
      unit: "A",
      direction: "up",
      baseValue: 28,
      healthyVariance: 0.6,
      warningDelta: 3.2,
      criticalDelta: 5.7,
      weight: 0.8,
    },
  ],
};
